url: https://rgb.sh
permalink: blog/:title/
theme: null

# Configure Layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Keep _site clean
exclude: ["CNAME", "Gemfile*", "LICENSE", "README.md", "rgb.sh.code-workspace", "serve.sh"]

plugins:
  - github-pages
  - jekyll-feed          # Atom (RSS) Feed
  - jekyll-redirect-from # Redirecting old paths
  - jekyll-seo-tag       # Metadata tags
  - jekyll-sitemap       # Generate sitemap.xml

# Atom (RSS) Feed
# https://github.com/jekyll/jekyll-feed
# Uses title, description and author below
# Defaults to /feed.xml
feed:
  excerpt_only: true

# Redirects
# https://github.com/jekyll/jekyll-redirect-from
# Don't need redirects.json in output
redirect_from:
  json: false

# SEO Tags
# https://github.com/jekyll/jekyll-seo-tag
# Note: Will be overwritten by post front matter.
title: rgb.sh
tagline: Seth Pendergrass
description: Seth Pendergrass's personal website.
author: Seth Pendergrass
logo: /favicon.ico
