url: https://rgb.sh
permalink: blog/:title
theme: null

# Configure Layouts
defaults:
  - scope:
      path: "*.html"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Keep _site clean
exclude: ["README.md", "LICENSE", "Gemfile*", "CNAME", "serve.sh"]

# Jekyll Feed
plugins:
  - jekyll-feed
title: rgb.sh
description: Seth Pendergrass's Blog
author: Seth Pendergrass
feed:
  excerpt_only: true