permalink: /:title
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
kramdown:
  parse_block_html: true
theme:
exclude: ["README.md", "LICENSE", "Gemfile*", "CNAME"]