permalink: blog/:title
defaults:
  - scope:
      path: "*.html"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
theme:
exclude: ["README.md", "LICENSE", "Gemfile*", "CNAME", "serve.sh"]